CREATE TABLE DEPARTMENT 
(DNO VARCHAR (20) PRIMARY KEY, 
DNAME VARCHAR (20), 
MGRSTARTDATE DATE); 

CREATE TABLE EMPLOYEE 
(SSN VARCHAR (20) PRIMARY KEY, 
FNAME VARCHAR (20), 
LNAME VARCHAR (20), 
ADDRESS VARCHAR (20), 
SEX CHAR (1), 
SALARY INTEGER, 
SUPERSSN VARCHAR (20) REFERENCES EMPLOYEE (SSN), 
DNO VARCHAR (20) REFERENCES DEPARTMENT (DNO));

ALTER TABLE DEPARTMENT 
ADD MGRSSN VARCHAR (20) REFERENCES EMPLOYEE (SSN); 

CREATE TABLE DLOCATION 
(DLOC VARCHAR (20), 
DNO REFERENCES DEPARTMENT (DNO), 
PRIMARY KEY (DNO, DLOC));

CREATE TABLE PROJECT 
(PNO INTEGER PRIMARY KEY, 
PNAME VARCHAR (20), 
PLOCATION VARCHAR (20), 
DNO VARCHAR (20) REFERENCES DEPARTMENT (DNO)); 

CREATE TABLE WORKS_ON 
(HOURS NUMBER (2), 
SSN VARCHAR (20) REFERENCES EMPLOYEE (SSN), 
PNO VARCHAR (20) REFERENCES PROJECT(PNO), 
PRIMARY KEY (SSN, PNO));

DESC EMPLOYEE; 
DESC DEPARTMENT;
DESC DLOCATION; 
DESC PROJECT;
DESC PROJECT; 
DESC WORKS_ON; 
