CREATE TABLE DEPARTMENT ( 
DNO VARCHAR (20) PRIMARY KEY, 
DNAME VARCHAR (20), 
MGRSTARTDATE DATE, 
MGRSSN VARCHAR (20)); 

CREATE TABLE EMPLOYEE ( 
SSN VARCHAR (20) PRIMARY KEY, 
FNAME VARCHAR (20), 
LNAME VARCHAR (20), 
ADDRESS VARCHAR (100), 
SEX CHAR (1), 
SALARY INT (10), 
SUPERSSN VARCHAR (20), 
DNO VARCHAR (20), 
FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE (SSN), 
FOREIGN KEY (DNO) REFERENCES DEPARTMENT (DNO)); 

ALTER TABLE DEPARTMENT ADD FOREIGN KEY(MGRSSN) REFERENCES 
EMPLOYEE(SSN); 

CREATE TABLE DLOCATION ( 
DLOC VARCHAR (20), 
DNO VARCHAR (20), 
PRIMARY KEY (DNO, DLOC), 
FOREIGN KEY (DNO) REFERENCES DEPARTMENT (DNO)); 

CREATE TABLE PROJECT ( 
PNO INT (10) PRIMARY KEY, 
PNAME VARCHAR (20), 
PLOCATION VARCHAR (20), 
DNO VARCHAR (20), 
FOREIGN KEY (DNO) REFERENCES DEPARTMENT (DNO)); 

CREATE TABLE WORKS_ON ( 
HOURS INT (4), 
SSN VARCHAR (20), 
PNO INT (10), 
PRIMARY KEY (SSN, PNO), 
FOREIGN KEY (SSN) REFERENCES EMPLOYEE (SSN), 
FOREIGN KEY (PNO) REFERENCES PROJECT (PNO)); 

DESC EMPLOYEE; 
DESC DEPARTMENT;
DESC DLOCATION; 
DESC PROJECT;
DESC WORKS_ON; 
